/**
 * Cities used for Marham directory listing harvest (/doctors/{city}).
 * Includes all app-supported cities plus common Punjab/smaller-city slugs on Marham.
 */
import { PAKISTAN_CITIES } from '../../../src/utils/constants.ts'

const EXTRA_MARHAM_CITY_SLUGS = [
  'gujrat',
  'jhelum',
  'sheikhupura',
  'kasur',
  'okara',
  'sahiwal',
  'rahim-yar-khan',
  'dera-ghazi-khan',
  'mandi-bahauddin',
  'chiniot',
  'vehari',
  'pakpattan',
  'narowal',
  'hafizabad',
  'mianwali',
  'bhakkar',
  'attock',
  'chakwal',
  'khushab',
  'jhang',
  'toba-tek-singh',
  'muzaffargarh',
  'khanewal',
  'lodhran',
  'bahawalnagar',
  'wah',
  'gojra',
  'burewala',
  'muridke',
  'kamoke',
  'kot-addu',
  'hasilpur',
  'swabi',
  'mingora',
  'kohat',
  'mardan',
  'nowshera',
  'larkana',
  'nawabshah',
  'mirpur-khas',
  'jacobabad',
  'taxila',
  'kotli',
  'skardu',
  'chitral',
  'shahkot',
  'chishtian',
  'kamalia',
  'dipalpur',
  'arifwala',
  'vihari',
  'layyah',
  'mailsi',
  'kotri',
  'daska',
  'wazirabad',
  'pasrur',
  'sambrial',
  'jaranwala',
  'pattoki',
  'renala-khurd',
  'murree',
  'talagang',
  'pind-dadan-khan',
  'kharian',
  'lalamusa',
  'dina',
  'kot-momin',
  'bhalwal',
  'sillanwali',
  'shorkot',
  'kabirwala',
  'ahmadpur-east',
  'liaquatpur',
  'fort-abbas',
  'haroonabad',
  'chichawatni',
  'sadiqabad',
  'jatoi',
  'mian-chanu',
] as const

export const MARHAM_LISTING_CITY_SLUGS: string[] = [
  ...new Set([
    ...PAKISTAN_CITIES.map((c) => c.value),
    ...EXTRA_MARHAM_CITY_SLUGS,
  ]),
].sort()
